# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\SysUser:
            algorithm: bcrypt
            cost: 12

    providers:
        db_provider:
            entity:
                class: AppBundle:SysUser            

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        
        main:
            pattern:    ^/            
            anonymous:  ~
            form_login:
                login_path: loginPage
                check_path: loginPage

            provider: db_provider

            logout:
                path:   logoutPage
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
