# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    util:
        class: AppBundle\Service\Util
        arguments: ['@doctrine.orm.entity_manager']
    # user_id_listener:
    #     class: AppBundle\EventListener\UserIdListener
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    error_redirect_listener:
        class: AppBundle\EventListener\ErrorRedirectListener
        arguments:
           router: "@router"
        tags:
           - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }