<?php

namespace AppBundle\Entity;

/**
 * ArrangementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrangementRepository extends \Doctrine\ORM\EntityRepository
{
	public function findRelevantToUser($user) {
		
	}
}
