<?php

namespace AppBundle\Entity;

/**
 * PatientArrangementReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientArrangementReferenceRepository extends \Doctrine\ORM\EntityRepository
{
	// public function findByArrangementCustom($arrangementId) {
	// 	$query = $this->getEntityManager() ->createQuery(
	// 		'SELECT ref, p FROM AppBundle:PatientArrangementReference ref JOIN ref.patient p
 //                WHERE ref.arrangement = :id'
	// 		)->setParameter('id', $arrangementId);
		
	// 	try {
	// 		return $query->getResult();
	// 	} catch (\Doctrine\ORM\NoResultException $e) { return null; } 
	// }

	// public function findByPatientCustom($patientId) {
	// 	$query = $this->getEntityManager() ->createQuery(
	// 		'SELECT ref, a FROM AppBundle:PatientArrangementReference ref JOIN ref.arrangement a
 //                WHERE ref.patient = :id'
	// 		)->setParameter('id', $patientId);
		
	// 	try {
	// 		return $query->getResult();
	// 	} catch (\Doctrine\ORM\NoResultException $e) { 
	// 		return null; 
	// 	} 
	// }
}
